/**
 * End-to-end match flow test
 *
 * THREE MODES:
 *
 *   WAIT MODE  (--wait)                             ← best full-flow test
 *     Bot joins the lobby with a visible name and waits for YOU to challenge it
 *     from the running app. Tests:
 *       ✓ Real WebRTC offer generated by the app and forwarded by signal server
 *       ✓ Answer forwarding back to the app
 *       ✓ request-match triggered by the app after receiving the answer
 *       ✓ match-start delivered to both sides
 *       ✓ Hole punch registration (bot side — app proxy handles the other side)
 *     The app launches the emulator on your machine via the normal Tauri path.
 *     NOTE: WebRTC P2P won't fully negotiate (Node has no native WebRTC stack),
 *     but the signaling and match flow are 100% real. The app still proceeds to
 *     match-start even when WebRTC setup fails gracefully.
 *
 *   CHALLENGE MODE  (--target <uid>)
 *     Bot challenges your real account directly via request-match (bypasses WebRTC).
 *     Good for quickly testing the match-start + hole punch path in isolation.
 *
 *   WEBRTC CHALLENGE MODE  (--webrtc --target <uid>)
 *     Bot discovers which lobbies the target is in, picks one at random, and sends
 *     a webrtc-ping-offer with that lobbyId. Tests the full challenge notification
 *     UI — you should see the popup in the correct lobby and can accept or decline.
 *
 *   RANKED QUEUE MODE  (--rank)
 *     Two bots enter the ranked queue and test the full matchmaking flow:
 *       ✓ Both bots matched via updateSocketState isRankQueued=true
 *       ✓ rank-queue-pending received by both
 *       ✓ Both send rank-queue-accept → match-start with isRanked=true
 *       ✓ Hole punch (both sides, optional)
 *     Sub-modes via --rank-decline: one bot declines → rank-queue-cancelled
 *     Sub-modes via --rank-timeout: neither accepts → rank-queue-timeout after 30s
 *
 *   BOT-VS-BOT MODE  (default, no --wait / --target)
 *     Two bots run the full server-side flow between themselves.
 *     Useful when the app isn't running.
 *
 * Prerequisites:
 *   - Signal server running    (npm run sockets)
 *   - Hole punch server running (npm run holepuncher)
 *   - For wait/challenge modes: app open and logged in
 *
 * Usage:
 *   npm run test:wait                          ← recommended first test
 *   npm run test:challenge                     ← quick match-start check
 *   npm run test:webrtc-challenge              ← challenge notification + lobby routing
 *   npm run test:rank                          ← ranked queue bot-vs-bot (both accept)
 *   npm run test:rank:decline                  ← ranked queue: one bot declines
 *   npm run test:rank:timeout                  ← ranked queue: timeout path (waits 30s)
 *   npm run test:signal                        ← signal server only, no other deps
 *   npm run test:punch                         ← signal + hole punch
 *   npm test -- <emulator-path>                ← bot-vs-bot with emulator
 *
 * All options:
 *   --wait               Wait-for-challenge mode
 *   --target <uid>       Challenge mode: your Firebase UID
 *   --webrtc             Use webrtc-ping-offer instead of request-match (requires --target)
 *   --rank               Ranked queue mode (two bots)
 *   --rank-decline       Ranked queue: Bot B declines the match
 *   --rank-timeout       Ranked queue: neither bot accepts (tests 30s timeout)
 *   --bot-name <name>    Bot display name  (default: TestBot)
 *   --game <rom>         ROM name          (default: sfiii3nr1)
 *   --skip-punch         Skip hole punch step
 *   --skip-emu           Bot-vs-bot: skip emulator launch
 */

import WebSocket from 'ws'
import dgram from 'dgram'
import { spawn, ChildProcess } from 'child_process'

// ── Config ────────────────────────────────────────────────────────────────────

const serverInfo = require('../../keys/server')

const DEFAULTS = {
  signalUrl: `ws://${serverInfo.COTURN_IP}:${serverInfo.SIGNAL_PORT ?? 3004}`,
  punchHost: serverInfo.COTURN_IP ?? '127.0.0.1',
  punchPort: Number(serverInfo.PUNCH_PORT ?? 33334),
  gameName:  'sfiii3nr1',
  delay:     0,
}

function parseArgs() {
  const argv = process.argv.slice(2)
  const cfg = {
    ...DEFAULTS,
    targetUid:    '',
    botName:      'TestBot',
    emulatorPath: '',
    luaPath:      '',
    waitMode:     false,
    webrtcMode:   false,
    rankMode:     false,
    rankDecline:  false,
    rankTimeout:  false,
    skipEmulator: false,
    skipPunch:    false,
  }
  for (let i = 0; i < argv.length; i++) {
    switch (argv[i]) {
      case '--wait':         cfg.waitMode     = true;           break
      case '--webrtc':       cfg.webrtcMode   = true;           break
      case '--rank':         cfg.rankMode     = true;           break
      case '--rank-decline': cfg.rankDecline  = true; cfg.rankMode = true; break
      case '--rank-timeout': cfg.rankTimeout  = true; cfg.rankMode = true; break
      case '--target':       cfg.targetUid    = argv[++i];      break
      case '--bot-name':   cfg.botName      = argv[++i];      break
      case '--game':       cfg.gameName     = argv[++i];      break
      case '--skip-emu':   cfg.skipEmulator = true;           break
      case '--skip-punch': cfg.skipPunch    = true;           break
      default:
        if (!argv[i].startsWith('--')) cfg.emulatorPath = argv[i]
    }
  }
  return cfg
}

// ── Logging ───────────────────────────────────────────────────────────────────

const ts   = () => new Date().toISOString().slice(11, 23)
const log  = (tag: string, msg: string) => console.log(`  [${ts()}] [${tag}] ${msg}`)
const ok   = (msg: string) => console.log(`\x1b[32m  ✓\x1b[0m ${msg}`)
const fail = (msg: string) => console.log(`\x1b[31m  ✗\x1b[0m ${msg}`)
const inf  = (msg: string) => console.log(`    ${msg}`)
const warn = (msg: string) => console.log(`\x1b[33m  !\x1b[0m ${msg}`)

function header(title: string) {
  console.log(`\n\x1b[36m── ${title} ${'─'.repeat(Math.max(0, 55 - title.length))}\x1b[0m`)
}

// ── WebSocket helpers ─────────────────────────────────────────────────────────

function wsConnect(url: string): Promise<WebSocket> {
  return new Promise((resolve, reject) => {
    const ws = new WebSocket(url)
    ws.once('open',  () => resolve(ws))
    ws.once('error', (e) => reject(new Error(`WS connect error: ${e.message}`)))
    setTimeout(() => reject(new Error(`WS connect timeout to ${url}`)), 6000)
  })
}

function waitFor(ws: WebSocket, predicate: (p: any) => boolean, timeoutMs = 15_000): Promise<any> {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      ws.off('message', handler)
      reject(new Error('waitFor timeout'))
    }, timeoutMs)
    const handler = (raw: WebSocket.RawData) => {
      try {
        const p = JSON.parse(raw.toString())
        if (predicate(p)) {
          clearTimeout(timer)
          ws.off('message', handler)
          resolve(p)
        }
      } catch {}
    }
    ws.on('message', handler)
  })
}

function wsSend(ws: WebSocket, payload: object) {
  ws.send(JSON.stringify(payload))
}

function disconnectBot(ws: WebSocket, uid: string) {
  try {
    if (ws.readyState === WebSocket.OPEN) {
      wsSend(ws, { type: 'userDisconnect', userUID: uid })
      ws.close()
    }
  } catch {}
}

// ── Hole punch ────────────────────────────────────────────────────────────────

type PeerInfo = { address: string; port: number; matchId: string }

function holePunch(uid: string, peerUid: string, host: string, port: number): Promise<PeerInfo> {
  return new Promise((resolve, reject) => {
    const sock = dgram.createSocket('udp4')
    const timer = setTimeout(() => {
      try { sock.close() } catch {}
      reject(new Error(`Hole punch timeout for ${uid} — is gopunchv1 running on ${host}:${port}?`))
    }, 15_000)

    sock.on('message', (msg) => {
      try {
        const p = JSON.parse(msg.toString())
        // Go server response: { peer: { uid, address, port }, matchId }
        if (p.peer?.address && p.peer?.port) {
          clearTimeout(timer)
          try { sock.close() } catch {}
          resolve({ address: p.peer.address, port: p.peer.port, matchId: p.matchId ?? '' })
        }
      } catch {}
    })
    sock.on('error', (e) => {
      clearTimeout(timer); try { sock.close() } catch {}
      reject(new Error(`UDP error for ${uid}: ${e.message}`))
    })
    sock.bind(0, () => {
      const buf = Buffer.from(JSON.stringify({ uid, peerUid, kill: false }))
      sock.send(buf, port, host, (e) => {
        if (e) { clearTimeout(timer); try { sock.close() } catch {}; reject(e) }
      })
    })
  })
}

// ── Emulator args (mirrors src/match/index.ts) ────────────────────────────────

function buildEmulatorArgs(opts: {
  emulatorPath: string; playerIndex: 1 | 2; localPort: number; remotePort: number
  playerName: string; delay: number; luaPath: string; rom: string
}): string[] {
  const { emulatorPath, playerIndex, localPort, remotePort, playerName, delay, luaPath, rom } = opts
  const normalized = emulatorPath.toLowerCase()
  const args: string[] = []
  if (normalized.endsWith('fs-fbneo.exe') || normalized.endsWith('fs-fbneo')) {
    args.push('--rom', rom)
    if (luaPath.trim()) args.push('--lua', luaPath)
    args.push('direct', '--player', String(playerIndex), '-n', playerName,
      '-l', `127.0.0.1:${localPort}`, '-r', `127.0.0.1:${remotePort}`, '-d', String(delay))
    return args
  }
  if (normalized.endsWith('fcadefbneo.exe') || normalized.endsWith('fcadefbneo')) {
    args.push(`quark:direct,${rom},${localPort},127.0.0.1,${remotePort},${playerIndex},${delay},0`)
    if (luaPath.trim()) args.push('--lua', luaPath)
    return args
  }
  args.push('--rom', rom, '--player', String(playerIndex), '-n', playerName,
    '-l', `127.0.0.1:${localPort}`, '-r', `127.0.0.1:${remotePort}`, '-d', String(delay))
  return args
}

// ── WAIT MODE ─────────────────────────────────────────────────────────────────
// Bot joins the lobby and waits for you to challenge it from the app.
// Your app generates the real WebRTC offer; the bot validates forwarding,
// sends a dummy answer, and waits for match-start.

async function runWaitMode(cfg: ReturnType<typeof parseArgs>) {
  const runId = Date.now()
  const BOT = {
    uid:            `test-bot-${runId}`,
    userName:       cfg.botName,
    accountElo:     1200,
    lobbyId:        'Hyper Reflector',
    userEmail:      'bot@test.local',
    countryCode:    'US',
    lastKnownPings: [] as any[],
  }

  console.log(`\n\x1b[1m=== Wait-for-Challenge Mode ===\x1b[0m`)
  inf(`Signal server : ${cfg.signalUrl}`)
  inf(`Hole punch    : ${cfg.punchHost}:${cfg.punchPort}${cfg.skipPunch ? ' (skipped)' : ''}`)
  inf(`Game          : ${cfg.gameName}`)

  // Step 1 — connect & join
  header('Step 1: Connect + Join Lobby')
  let ws!: WebSocket
  try {
    ws = await wsConnect(cfg.signalUrl)
    ok('Connected to signal server')
  } catch (e: any) {
    fail(`Connection failed: ${e.message}`)
    process.exit(1)
  }

  wsSend(ws, { type: 'join', user: BOT, lobbyId: BOT.lobbyId })
  try {
    await waitFor(ws, p => p.type === 'connected-users')
    ok(`Bot joined "${BOT.lobbyId}"`)
  } catch (e: any) {
    fail(`Join failed: ${e.message}`)
    disconnectBot(ws, BOT.uid)
    process.exit(1)
  }

  // Step 2 — wait for challenge
  header('Step 2: Waiting for Challenge')
  console.log(`\n  \x1b[1mAction required:\x1b[0m Open the app and challenge \x1b[33m"${BOT.userName}"\x1b[0m`)
  inf(`  (Bot UID: ${BOT.uid})`)
  inf(`  Waiting up to 60 seconds...\n`)

  let offer: any
  let challengerUid: string
  try {
    const msg = await waitFor(ws, p => p.type === 'webrtc-ping-offer', 60_000)
    offer        = msg.offer
    challengerUid = msg.from
    ok(`Received real WebRTC offer from ${challengerUid}`)
    inf(`Offer type: ${offer?.type ?? 'unknown'}`)
    inf(`SDP length: ${offer?.sdp?.length ?? 0} chars — ${offer?.sdp?.length > 100 ? 'looks real ✓' : 'suspiciously short'}`)
  } catch (e: any) {
    fail(`No offer received within 60s: ${e.message}`)
    disconnectBot(ws, BOT.uid)
    process.exit(1)
  }

  // Step 3 — send answer back
  // A dummy answer is enough: the app sends request-match regardless of whether
  // setRemoteDescription succeeds (the error is caught and logged, not fatal).
  header('Step 3: Answer + Signal Forwarding')
  const dummyAnswer = { type: 'answer', sdp: 'v=0\r\n' }
  wsSend(ws, { type: 'webrtc-ping-answer', from: BOT.uid, to: challengerUid, answer: dummyAnswer })
  ok('Answer forwarded to signal server (dummy SDP — WebRTC P2P will not establish, but match flow continues)')

  // Step 4 — wait for match-start (app sends request-match after receiving answer)
  header('Step 4: Match Start')
  inf('Waiting for the app to send request-match and for server to issue match-start...')
  let matchStart: any
  try {
    matchStart = await waitFor(ws, p => p.type === 'match-start')
    ok('match-start received on bot side')
    inf(`Match ID  : ${matchStart.matchId}`)
    inf(`Bot slot  : ${matchStart.playerSlot}`)
    inf(`Opponent  : ${matchStart.opponentUid}`)
    inf(`Server    : ${matchStart.serverHost}:${matchStart.serverPort}`)
  } catch (e: any) {
    fail(`match-start not received: ${e.message}`)
    inf('The app may not have sent request-match. Check the browser console for WebRTC errors.')
    disconnectBot(ws, BOT.uid)
    process.exit(1)
  }

  // Step 5 — hole punch (bot side)
  if (!cfg.skipPunch) {
    header('Step 5: Hole Punch (bot side)')
    inf(`Registering bot with ${cfg.punchHost}:${cfg.punchPort}...`)
    inf('The app Rust proxy is registering the other side — waiting for the pair...')
    try {
      const peer = await holePunch(BOT.uid, challengerUid, cfg.punchHost, cfg.punchPort)
      ok('Hole punch exchange complete')
      inf(`Bot sees you at ${peer.address}:${peer.port}`)
      inf(`matchId from punch server: ${peer.matchId || 'n/a'}`)
    } catch (e: any) {
      fail(`Hole punch failed: ${e.message}`)
      warn('The emulator may still have launched if the app proxy timed out independently.')
    }
  } else {
    header('Step 5: Hole Punch')
    inf('Skipped (--skip-punch)')
  }

  console.log('\n\x1b[32m✓ Full flow validated.\x1b[0m')
  inf('The emulator should be launching on your machine via the app.')
  inf('Watching for match-force-close. Press Ctrl+C to exit early.\n')

  // Stay alive — watch for match end
  const cleanup = (reason: string) => {
    log('cleanup', reason)
    try { wsSend(ws, { type: 'matchEnd', userUID: BOT.uid }) } catch {}
    setTimeout(() => { disconnectBot(ws, BOT.uid); process.exit(0) }, 300)
  }

  ws.on('message', (raw) => {
    try {
      const p = JSON.parse(raw.toString())
      if (p.type === 'match-force-close') {
        ok(`match-force-close received (reason: ${p.reason ?? 'unknown'}) — server cleanup confirmed`)
        cleanup('match ended')
      }
    } catch {}
  })
  ws.on('close', () => process.exit(0))
  process.on('SIGINT', () => cleanup('interrupted'))
}

// ── CHALLENGE MODE ────────────────────────────────────────────────────────────
// Bot discovers which lobbies the target is in, picks one randomly, and sends
// request-match directly to your real UID (bypasses WebRTC).

async function runChallengeMode(cfg: ReturnType<typeof parseArgs>) {
  const runId = Date.now()
  const INITIAL_LOBBY = 'Hyper Reflector'
  const BOT = {
    uid:            `test-bot-${runId}`,
    userName:       cfg.botName,
    accountElo:     1200,
    lobbyId:        INITIAL_LOBBY,
    userEmail:      'bot@test.local',
    countryCode:    'US',
    lastKnownPings: [] as any[],
  }

  console.log(`\n\x1b[1m=== Challenge Mode ===\x1b[0m`)
  inf(`Signal server : ${cfg.signalUrl}`)
  inf(`Hole punch    : ${cfg.punchHost}:${cfg.punchPort}${cfg.skipPunch ? ' (skipped)' : ''}`)
  inf(`Target UID    : ${cfg.targetUid}`)
  inf(`Game          : ${cfg.gameName}`)

  header('Step 1: Connect + Join')
  let ws!: WebSocket
  try {
    ws = await wsConnect(cfg.signalUrl)
    ok('Connected')
  } catch (e: any) {
    fail(`Connection failed: ${e.message}`)
    process.exit(1)
  }

  // Collect lobby membership from connected-users broadcasts (which include lobbyId)
  const lobbyUsers = new Map<string, string[]>()
  let lobbyCounts: any[] = []
  const lobbyDataHandler = (raw: WebSocket.RawData) => {
    try {
      const p = JSON.parse(raw.toString())
      if (p.type === 'connected-users' && p.lobbyId) {
        lobbyUsers.set(p.lobbyId, (p.users ?? []).map((u: any) => u.uid))
      }
      if (p.type === 'lobby-user-counts' && p.updates) {
        lobbyCounts = p.updates
      }
    } catch {}
  }
  ws.on('message', lobbyDataHandler)

  wsSend(ws, { type: 'join', user: BOT, lobbyId: INITIAL_LOBBY })
  try {
    await waitFor(ws, p => p.type === 'connected-users')
    ok(`Bot joined "${INITIAL_LOBBY}"`)
  } catch (e: any) {
    fail(`Join failed: ${e.message}`)
    disconnectBot(ws, BOT.uid); process.exit(1)
  }

  // Wait for lobby-user-counts to arrive after join
  await new Promise(r => setTimeout(r, 500))

  header('Step 2: Discover Target Lobbies')
  // Subscribe to all non-private lobbies (up to 4 more since we're already in one)
  const toSubscribe = lobbyCounts
    .filter((l: any) => l.name !== INITIAL_LOBBY && !l.isPrivate && l.users > 0)
    .map((l: any) => l.name as string)
    .slice(0, 4)

  if (toSubscribe.length > 0) {
    inf(`Subscribing to ${toSubscribe.length} additional lobby(ies) to find target...`)
    for (const lobbyId of toSubscribe) {
      wsSend(ws, { type: 'subscribeLobby', lobbyId, user: BOT })
    }
    await new Promise(r => setTimeout(r, 1500))
  }

  ws.off('message', lobbyDataHandler)

  const targetLobbies = [...lobbyUsers.entries()]
    .filter(([, uids]) => uids.includes(cfg.targetUid))
    .map(([lobbyId]) => lobbyId)

  if (targetLobbies.length === 0) {
    fail(`Target ${cfg.targetUid} not found in any visible lobby — make sure the app is open and logged in`)
    disconnectBot(ws, BOT.uid); process.exit(1)
  }

  const chosenLobby = targetLobbies[Math.floor(Math.random() * targetLobbies.length)]
  ok(`Target found in ${targetLobbies.length} lobby(ies): ${targetLobbies.join(', ')}`)
  ok(`Chosen lobby: "${chosenLobby}"`)

  header('Step 3: Request Match')
  wsSend(ws, {
    type: 'sendMessage',
    sender: { uid: BOT.uid, userName: BOT.userName, lobbyId: chosenLobby },
    message: "Here's johnny!",
  })
  log('info', `Bot challenging ${cfg.targetUid} in "${chosenLobby}"...`)
  wsSend(ws, {
    type: 'request-match',
    challengerId: BOT.uid,
    opponentId:   cfg.targetUid,
    requestedBy:  BOT.uid,
    lobbyId:      chosenLobby,
    gameName:     cfg.gameName,
  })

  let matchStart: any
  try {
    matchStart = await waitFor(ws, p => p.type === 'match-start' && p.opponentUid === cfg.targetUid)
    ok('match-start received')
    inf(`Match ID : ${matchStart.matchId}`)
    inf(`Bot slot : ${matchStart.playerSlot}`)
    inf(`Server   : ${matchStart.serverHost}:${matchStart.serverPort}`)
  } catch (e: any) {
    fail(`match-start not received: ${e.message}`)
    inf('Make sure the target is connected and not already in a match.')
    disconnectBot(ws, BOT.uid); process.exit(1)
  }

  if (!cfg.skipPunch) {
    header('Step 4: Hole Punch (bot side)')
    inf(`Registering with ${cfg.punchHost}:${cfg.punchPort}...`)
    try {
      const peer = await holePunch(BOT.uid, cfg.targetUid, cfg.punchHost, cfg.punchPort)
      ok('Hole punch complete')
      inf(`Bot sees target at ${peer.address}:${peer.port}`)
    } catch (e: any) {
      fail(`Hole punch failed: ${e.message}`)
    }
  }

  console.log('\n\x1b[32m✓ Challenge complete — emulator should be launching on your machine.\x1b[0m')
  inf('Press Ctrl+C to exit.\n')

  const cleanup = () => {
    try { wsSend(ws, { type: 'matchEnd', userUID: BOT.uid }) } catch {}
    setTimeout(() => { disconnectBot(ws, BOT.uid); process.exit(0) }, 300)
  }
  ws.on('message', (raw) => {
    try {
      const p = JSON.parse(raw.toString())
      if (p.type === 'match-force-close') { ok('match-force-close received'); cleanup() }
    } catch {}
  })
  ws.on('close', () => process.exit(0))
  process.on('SIGINT', () => cleanup())
}

// ── BOT-VS-BOT MODE ───────────────────────────────────────────────────────────

async function runBotVsBotMode(cfg: ReturnType<typeof parseArgs>) {
  const runId = Date.now()
  const BOT_A = { uid: `test-bot-a-${runId}`, userName: 'TestBotA', accountElo: 1200, lobbyId: 'Hyper Reflector', userEmail: 'bota@test.local', countryCode: 'US', lastKnownPings: [] as any[] }
  const BOT_B = { uid: `test-bot-b-${runId}`, userName: 'TestBotB', accountElo: 1200, lobbyId: 'Hyper Reflector', userEmail: 'botb@test.local', countryCode: 'US', lastKnownPings: [] as any[] }

  console.log(`\n\x1b[1m=== Bot-vs-Bot Mode ===\x1b[0m`)
  inf(`Signal server : ${cfg.signalUrl}`)
  inf(`Hole punch    : ${cfg.punchHost}:${cfg.punchPort}${cfg.skipPunch ? ' (skipped)' : ''}`)
  inf(`Emulator      : ${cfg.emulatorPath || '(not provided)'}${cfg.skipEmulator ? ' (skipped)' : ''}`)
  inf(`Game          : ${cfg.gameName}`)

  let wsA!: WebSocket, wsB!: WebSocket

  header('Step 1: Connect')
  try {
    ;[wsA, wsB] = await Promise.all([wsConnect(cfg.signalUrl), wsConnect(cfg.signalUrl)])
    ok('Both bots connected')
  } catch (e: any) {
    fail(`Connection failed: ${e.message}`); process.exit(1)
  }

  header('Step 2: Join Lobby')
  wsSend(wsA, { type: 'join', user: BOT_A, lobbyId: BOT_A.lobbyId })
  wsSend(wsB, { type: 'join', user: BOT_B, lobbyId: BOT_B.lobbyId })
  try {
    await Promise.all([
      waitFor(wsA, p => p.type === 'connected-users'),
      waitFor(wsB, p => p.type === 'connected-users'),
    ])
    ok(`Both bots joined "${BOT_A.lobbyId}"`)
  } catch (e: any) {
    fail(`Join failed: ${e.message}`)
    disconnectBot(wsA, BOT_A.uid); disconnectBot(wsB, BOT_B.uid); process.exit(1)
  }

  await new Promise(r => setTimeout(r, 200))

  header('Step 3: WebRTC Signal Forwarding')
  wsSend(wsB, { type: 'webrtc-ping-offer', from: BOT_B.uid, to: BOT_A.uid, offer: { type: 'offer', sdp: 'v=0\r\n' } })
  try {
    await waitFor(wsA, p => p.type === 'webrtc-ping-offer' && p.from === BOT_B.uid)
    ok('Offer forwarded to Bot A')
  } catch (e: any) {
    fail(`Offer not forwarded: ${e.message}`)
    disconnectBot(wsA, BOT_A.uid); disconnectBot(wsB, BOT_B.uid); process.exit(1)
  }

  wsSend(wsA, { type: 'webrtc-ping-answer', from: BOT_A.uid, to: BOT_B.uid, answer: { type: 'answer', sdp: 'v=0\r\n' } })
  try {
    await waitFor(wsB, p => p.type === 'webrtc-ping-answer' && p.from === BOT_A.uid)
    ok('Answer forwarded to Bot B')
  } catch (e: any) {
    fail(`Answer not forwarded: ${e.message}`)
    disconnectBot(wsA, BOT_A.uid); disconnectBot(wsB, BOT_B.uid); process.exit(1)
  }

  header('Step 4: Request Match')
  wsSend(wsA, { type: 'request-match', challengerId: BOT_A.uid, opponentId: BOT_B.uid, requestedBy: BOT_A.uid, lobbyId: BOT_A.lobbyId, gameName: cfg.gameName })

  let matchStartA: any, matchStartB: any
  try {
    ;[matchStartA, matchStartB] = await Promise.all([
      waitFor(wsA, p => p.type === 'match-start'),
      waitFor(wsB, p => p.type === 'match-start'),
    ])
    ok('Match created')
    inf(`Match ID : ${matchStartA.matchId}`)
    inf(`Slots    : A=${matchStartA.playerSlot}  B=${matchStartB.playerSlot}`)
    inf(`Server   : ${matchStartA.serverHost}:${matchStartA.serverPort}`)
  } catch (e: any) {
    fail(`match-start not received: ${e.message}`)
    disconnectBot(wsA, BOT_A.uid); disconnectBot(wsB, BOT_B.uid); process.exit(1)
  }

  if (!cfg.skipPunch) {
    header('Step 5: Hole Punch')
    log('info', `Both bots registering with ${cfg.punchHost}:${cfg.punchPort}...`)
    try {
      const [peerA, peerB] = await Promise.all([
        holePunch(BOT_A.uid, BOT_B.uid, cfg.punchHost, cfg.punchPort),
        holePunch(BOT_B.uid, BOT_A.uid, cfg.punchHost, cfg.punchPort),
      ])
      ok('Hole punch exchange complete')
      inf(`Bot A sees Bot B at ${peerA.address}:${peerA.port}`)
      inf(`Bot B sees Bot A at ${peerB.address}:${peerB.port}`)
    } catch (e: any) {
      fail(`Hole punch failed: ${e.message}`)
      disconnectBot(wsA, BOT_A.uid); disconnectBot(wsB, BOT_B.uid); process.exit(1)
    }
  } else {
    header('Step 5: Hole Punch'); inf('Skipped (--skip-punch)')
  }

  header('Step 6: Emulator Launch')
  if (cfg.skipEmulator || !cfg.emulatorPath.trim()) {
    inf('Skipped')
    console.log('\n\x1b[32m✓ All requested steps passed.\x1b[0m\n')
    disconnectBot(wsA, BOT_A.uid); disconnectBot(wsB, BOT_B.uid)
    return
  }

  const slotA: 0 | 1 = matchStartA.playerSlot === 0 ? 0 : 1
  const slotB: 0 | 1 = slotA === 0 ? 1 : 0
  const argsA = buildEmulatorArgs({ emulatorPath: cfg.emulatorPath, playerIndex: (slotA + 1) as 1 | 2, localPort: slotA === 0 ? 7000 : 7001, remotePort: slotA === 0 ? 7001 : 7000, playerName: BOT_A.userName, delay: cfg.delay, luaPath: cfg.luaPath, rom: cfg.gameName })
  const argsB = buildEmulatorArgs({ emulatorPath: cfg.emulatorPath, playerIndex: (slotB + 1) as 1 | 2, localPort: slotB === 0 ? 7000 : 7001, remotePort: slotB === 0 ? 7001 : 7000, playerName: BOT_B.userName, delay: cfg.delay, luaPath: cfg.luaPath, rom: cfg.gameName })

  let emuA!: ChildProcess, emuB!: ChildProcess
  try {
    emuA = spawn(cfg.emulatorPath, argsA, { detached: false, stdio: 'ignore' })
    emuB = spawn(cfg.emulatorPath, argsB, { detached: false, stdio: 'ignore' })
    emuA.on('error', (e) => log('emuA', `error: ${e.message}`))
    emuB.on('error', (e) => log('emuB', `error: ${e.message}`))
    ok(`Emulator A (PID ${emuA.pid}, Player ${slotA + 1})`)
    ok(`Emulator B (PID ${emuB.pid}, Player ${slotB + 1})`)
  } catch (e: any) {
    fail(`Spawn failed: ${e.message}`)
    disconnectBot(wsA, BOT_A.uid); disconnectBot(wsB, BOT_B.uid); process.exit(1)
  }

  console.log('\n\x1b[32m✓ All steps passed.\x1b[0m  Close emulator windows when done.\n')

  let closed = 0
  const onClose = (label: string) => {
    closed++; log(label, 'exited')
    if (closed >= 2) {
      try { wsSend(wsA, { type: 'matchEnd', userUID: BOT_A.uid }) } catch {}
      try { wsSend(wsB, { type: 'matchEnd', userUID: BOT_B.uid }) } catch {}
      setTimeout(() => { disconnectBot(wsA, BOT_A.uid); disconnectBot(wsB, BOT_B.uid); process.exit(0) }, 300)
    }
  }
  emuA.on('close', () => onClose('emuA'))
  emuB.on('close', () => onClose('emuB'))
  process.on('SIGINT', () => {
    try { emuA?.kill() } catch {}; try { emuB?.kill() } catch {}
    disconnectBot(wsA, BOT_A.uid); disconnectBot(wsB, BOT_B.uid); process.exit(0)
  })
}

// ── WEBRTC CHALLENGE MODE ─────────────────────────────────────────────────────
// Bot discovers which lobbies the target is in, picks one at random, and sends
// a webrtc-ping-offer with that lobbyId. The target should see the challenge
// notification in the correct lobby and can accept or decline manually.

async function runWebrtcChallengeMode(cfg: ReturnType<typeof parseArgs>) {
  const runId = Date.now()
  const INITIAL_LOBBY = 'Hyper Reflector'
  const BOT = {
    uid:            `test-bot-${runId}`,
    userName:       cfg.botName,
    accountElo:     1200,
    lobbyId:        INITIAL_LOBBY,
    userEmail:      'bot@test.local',
    countryCode:    'US',
    lastKnownPings: [] as any[],
  }

  console.log(`\n\x1b[1m=== WebRTC Challenge Mode ===\x1b[0m`)
  inf(`Signal server : ${cfg.signalUrl}`)
  inf(`Target UID    : ${cfg.targetUid}`)
  inf(`Game          : ${cfg.gameName}`)

  header('Step 1: Connect + Join')
  let ws!: WebSocket
  try {
    ws = await wsConnect(cfg.signalUrl)
    ok('Connected')
  } catch (e: any) {
    fail(`Connection failed: ${e.message}`)
    process.exit(1)
  }

  const lobbyUsers = new Map<string, string[]>()
  let lobbyCounts: any[] = []
  const lobbyDataHandler = (raw: WebSocket.RawData) => {
    try {
      const p = JSON.parse(raw.toString())
      if (p.type === 'connected-users' && p.lobbyId) {
        lobbyUsers.set(p.lobbyId, (p.users ?? []).map((u: any) => u.uid))
      }
      if (p.type === 'lobby-user-counts' && p.updates) {
        lobbyCounts = p.updates
      }
    } catch {}
  }
  ws.on('message', lobbyDataHandler)

  wsSend(ws, { type: 'join', user: BOT, lobbyId: INITIAL_LOBBY })
  try {
    await waitFor(ws, p => p.type === 'connected-users')
    ok(`Bot joined "${INITIAL_LOBBY}"`)
  } catch (e: any) {
    fail(`Join failed: ${e.message}`)
    disconnectBot(ws, BOT.uid); process.exit(1)
  }

  await new Promise(r => setTimeout(r, 500))

  header('Step 2: Discover Target Lobbies')
  const toSubscribe = lobbyCounts
    .filter((l: any) => l.name !== INITIAL_LOBBY && !l.isPrivate && l.users > 0)
    .map((l: any) => l.name as string)
    .slice(0, 4)

  if (toSubscribe.length > 0) {
    inf(`Subscribing to ${toSubscribe.length} additional lobby(ies) to find target...`)
    for (const lobbyId of toSubscribe) {
      wsSend(ws, { type: 'subscribeLobby', lobbyId, user: BOT })
    }
    await new Promise(r => setTimeout(r, 1500))
  }

  ws.off('message', lobbyDataHandler)

  const targetLobbies = [...lobbyUsers.entries()]
    .filter(([, uids]) => uids.includes(cfg.targetUid))
    .map(([lobbyId]) => lobbyId)

  if (targetLobbies.length === 0) {
    fail(`Target ${cfg.targetUid} not found in any visible lobby — make sure the app is open and logged in`)
    disconnectBot(ws, BOT.uid); process.exit(1)
  }

  const chosenLobby = targetLobbies[Math.floor(Math.random() * targetLobbies.length)]
  ok(`Target found in ${targetLobbies.length} lobby(ies): ${targetLobbies.join(', ')}`)
  ok(`Chosen lobby: "${chosenLobby}"`)

  header('Step 3: Send WebRTC Offer')
  wsSend(ws, {
    type: 'sendMessage',
    sender: { uid: BOT.uid, userName: BOT.userName, lobbyId: chosenLobby },
    message: "Here's johnny!",
  })
  const dummyOffer = { type: 'offer', sdp: 'v=0\r\n' }
  wsSend(ws, {
    type:    'webrtc-ping-offer',
    to:      cfg.targetUid,
    from:    BOT.uid,
    offer:   dummyOffer,
    lobbyId: chosenLobby,
  })
  ok(`webrtc-ping-offer sent to ${cfg.targetUid} with lobbyId "${chosenLobby}"`)
  console.log(`\n  \x1b[1mAction required:\x1b[0m Check the app — the challenge notification should appear in \x1b[33m"${chosenLobby}"\x1b[0m`)
  inf('  Accept or Decline the challenge. Waiting up to 60 seconds...')
  inf('  Note: WebRTC will not fully negotiate (bot uses a dummy SDP), but the notification')
  inf('  routing and accept/decline flow are fully tested.\n')

  header('Step 4: Waiting for Response')
  try {
    const response = await waitFor(
      ws,
      p => (p.type === 'webrtc-ping-answer' || p.type === 'webrtc-ping-decline') && p.from === cfg.targetUid,
      60_000
    )
    if (response.type === 'webrtc-ping-answer') {
      ok('webrtc-ping-answer received — challenge accepted and answer sent back')
    } else {
      ok('webrtc-ping-decline received — challenge was declined (or WebRTC setup failed after accept)')
    }
    ok('Challenge notification flow confirmed for lobby: ' + chosenLobby)
  } catch (e: any) {
    fail(`No response within 60s: ${e.message}`)
    inf('The notification may not have appeared, or the lobby routing may be incorrect.')
    disconnectBot(ws, BOT.uid); process.exit(1)
  }

  console.log('\n\x1b[32m✓ WebRTC challenge notification flow confirmed.\x1b[0m\n')
  disconnectBot(ws, BOT.uid)
}

// ── RANKED QUEUE MODE ─────────────────────────────────────────────────────────
// Two bots enter the ranked queue and exercise the full matchmaking flow.
// --rank-decline: Bot B declines → both receive rank-queue-cancelled
// --rank-timeout: neither accepts → both receive rank-queue-timeout after 30s
// default:        both accept    → match-start with isRanked=true

async function runRankQueueMode(cfg: ReturnType<typeof parseArgs>) {
  const runId = Date.now()
  const BOT_A = {
    uid:            `rank-bot-a-${runId}`,
    userName:       `${cfg.botName}A`,
    accountElo:     1200,
    lobbyId:        'Hyper Reflector',
    userEmail:      'rank-a@test.local',
    countryCode:    'US',
    lastKnownPings: [] as any[],
  }
  const BOT_B = {
    uid:            `rank-bot-b-${runId}`,
    userName:       `${cfg.botName}B`,
    accountElo:     1200,
    lobbyId:        'Hyper Reflector',
    userEmail:      'rank-b@test.local',
    countryCode:    'US',
    lastKnownPings: [] as any[],
  }

  const subMode = cfg.rankDecline ? 'decline' : cfg.rankTimeout ? 'timeout' : 'accept'
  console.log(`\n\x1b[1m=== Ranked Queue Mode (${subMode}) ===\x1b[0m`)
  inf(`Signal server : ${cfg.signalUrl}`)
  inf(`Hole punch    : ${cfg.punchHost}:${cfg.punchPort}${cfg.skipPunch ? ' (skipped)' : ''}`)
  inf(`Game          : ${cfg.gameName}`)

  // Cleanup helper — call from every exit path (success, failure, and SIGINT)
  let cleanedUp = false
  let matchStarted = false
  const cleanup = (withMatchEnd = matchStarted) => {
    if (cleanedUp) return
    cleanedUp = true
    if (withMatchEnd) {
      try { wsSend(wsA, { type: 'matchEnd', userUID: BOT_A.uid }) } catch {}
      try { wsSend(wsB, { type: 'matchEnd', userUID: BOT_B.uid }) } catch {}
    }
    setTimeout(() => {
      disconnectBot(wsA, BOT_A.uid)
      disconnectBot(wsB, BOT_B.uid)
      process.exit(0)
    }, 300)
  }
  const cleanupAndFail = () => {
    if (cleanedUp) return
    cleanedUp = true
    disconnectBot(wsA, BOT_A.uid)
    disconnectBot(wsB, BOT_B.uid)
    process.exit(1)
  }
  process.on('SIGINT', () => { log('cleanup', 'interrupted'); cleanup(false) })

  // Step 1 — connect both bots
  header('Step 1: Connect')
  let wsA!: WebSocket, wsB!: WebSocket
  try {
    ;[wsA, wsB] = await Promise.all([wsConnect(cfg.signalUrl), wsConnect(cfg.signalUrl)])
    ok('Both bots connected')
  } catch (e: any) {
    fail(`Connection failed: ${e.message}`); process.exit(1)
  }

  // Step 2 — join lobby
  header('Step 2: Join Lobby')
  wsSend(wsA, { type: 'join', user: BOT_A, lobbyId: BOT_A.lobbyId })
  wsSend(wsB, { type: 'join', user: BOT_B, lobbyId: BOT_B.lobbyId })
  try {
    await Promise.all([
      waitFor(wsA, p => p.type === 'connected-users'),
      waitFor(wsB, p => p.type === 'connected-users'),
    ])
    ok(`Both bots joined "${BOT_A.lobbyId}"`)
  } catch (e: any) {
    fail(`Join failed: ${e.message}`)
    cleanupAndFail()
  }

  await new Promise(r => setTimeout(r, 200))

  // Step 3 — enter ranked queue
  // Use a unique game name derived from the run ID so these two bots can only
  // ever match each other — prevents one bot from pairing with a real player
  // who happens to be queuing with the same game.
  const rankTestGame = `rank-bot-test-${runId}`
  header('Step 3: Enter Ranked Queue')
  inf(`Queue game name: "${rankTestGame}" (isolated per run)`)
  const queuePayload = (uid: string, lobbyId: string) => ({
    type: 'updateSocketState',
    data: {
      uid,
      lobbyId,
      stateToUpdate: { key: 'isRankQueued', value: true },
      rankQueueGameName: rankTestGame,
    },
  })
  wsSend(wsA, queuePayload(BOT_A.uid, BOT_A.lobbyId))
  wsSend(wsB, queuePayload(BOT_B.uid, BOT_B.lobbyId))
  ok('Both bots queued — waiting for rank-queue-pending...')

  // Step 4 — wait for match found
  header('Step 4: Match Found')
  let pendingA: any
  try {
    ;[pendingA] = await Promise.all([
      waitFor(wsA, p => p.type === 'rank-queue-pending'),
      waitFor(wsB, p => p.type === 'rank-queue-pending'),
    ])
    ok('rank-queue-pending received by both bots')
    inf(`Match ID   : ${pendingA.matchId}`)
    inf(`Player A   : ${pendingA.playerA?.userName} (uid: ${pendingA.playerA?.uid})`)
    inf(`Player B   : ${pendingA.playerB?.userName} (uid: ${pendingA.playerB?.uid})`)
  } catch (e: any) {
    fail(`rank-queue-pending not received: ${e.message}`)
    cleanupAndFail()
  }

  const matchId: string = pendingA.matchId

  // Sanity check: ensure the match is between our two bots, not a real player
  const matchedUids = new Set([pendingA.playerA?.uid, pendingA.playerB?.uid])
  if (!matchedUids.has(BOT_A.uid) || !matchedUids.has(BOT_B.uid)) {
    fail(`Matched unexpected opponents: ${[...matchedUids].join(' vs ')} — expected our two bots`)
    inf('This should not happen with the isolated game name. Check for stale server state.')
    cleanupAndFail()
  }

  // Step 5 — respond based on sub-mode
  if (cfg.rankTimeout) {
    header('Step 5: Timeout Path (waiting up to 35s)')
    inf('Neither bot will accept — waiting for rank-queue-timeout...')
    try {
      const [timeoutA] = await Promise.all([
        waitFor(wsA, p => p.type === 'rank-queue-timeout' && p.matchId === matchId, 35_000),
        waitFor(wsB, p => p.type === 'rank-queue-timeout' && p.matchId === matchId, 35_000),
      ])
      ok('rank-queue-timeout received by both bots')
      inf(`Match ID: ${timeoutA.matchId}`)
    } catch (e: any) {
      fail(`rank-queue-timeout not received: ${e.message}`)
      cleanupAndFail()
    }
    console.log('\n\x1b[32m✓ Ranked queue timeout path confirmed.\x1b[0m\n')
    cleanup(false)
    return
  }

  if (cfg.rankDecline) {
    header('Step 5: Decline Path')
    inf('Bot B declining...')
    wsSend(wsB, { type: 'rank-queue-decline', matchId, uid: BOT_B.uid })
    try {
      const [cancelA, cancelB] = await Promise.all([
        waitFor(wsA, p => p.type === 'rank-queue-cancelled' && p.matchId === matchId),
        waitFor(wsB, p => p.type === 'rank-queue-cancelled' && p.matchId === matchId),
      ])
      ok('rank-queue-cancelled received by both bots')
      inf(`Bot A reason: ${cancelA.reason}`)
      inf(`Bot B reason: ${cancelB.reason}`)
    } catch (e: any) {
      fail(`rank-queue-cancelled not received: ${e.message}`)
      cleanupAndFail()
    }
    console.log('\n\x1b[32m✓ Ranked queue decline path confirmed.\x1b[0m\n')
    cleanup(false)
    return
  }

  // Default: both accept
  header('Step 5: Both Accept')
  matchStarted = true
  wsSend(wsA, { type: 'rank-queue-accept', matchId, uid: BOT_A.uid })
  wsSend(wsB, { type: 'rank-queue-accept', matchId, uid: BOT_B.uid })

  let matchStartA: any, matchStartB: any
  try {
    ;[matchStartA, matchStartB] = await Promise.all([
      waitFor(wsA, p => p.type === 'match-start' && p.matchId === matchId),
      waitFor(wsB, p => p.type === 'match-start' && p.matchId === matchId),
    ])
    ok('match-start received by both bots')
    inf(`Match ID  : ${matchStartA.matchId}`)
    inf(`Slots     : A=${matchStartA.playerSlot}  B=${matchStartB.playerSlot}`)
    inf(`isRanked  : ${matchStartA.isRanked}`)
    inf(`Server    : ${matchStartA.serverHost}:${matchStartA.serverPort}`)
    if (!matchStartA.isRanked) warn('isRanked flag is missing or false on match-start')
  } catch (e: any) {
    fail(`match-start not received: ${e.message}`)
    cleanupAndFail()
  }

  if (!cfg.skipPunch) {
    header('Step 6: Hole Punch')
    log('info', `Both bots registering with ${cfg.punchHost}:${cfg.punchPort}...`)
    try {
      const [peerA, peerB] = await Promise.all([
        holePunch(BOT_A.uid, BOT_B.uid, cfg.punchHost, cfg.punchPort),
        holePunch(BOT_B.uid, BOT_A.uid, cfg.punchHost, cfg.punchPort),
      ])
      ok('Hole punch exchange complete')
      inf(`Bot A sees Bot B at ${peerA.address}:${peerA.port}`)
      inf(`Bot B sees Bot A at ${peerB.address}:${peerB.port}`)
    } catch (e: any) {
      fail(`Hole punch failed: ${e.message}`)
      cleanupAndFail()
    }
  } else {
    header('Step 6: Hole Punch'); inf('Skipped (--skip-punch)')
  }

  console.log('\n\x1b[32m✓ Ranked queue accept path confirmed.\x1b[0m\n')
  cleanup(true)
}

// ── Entry ─────────────────────────────────────────────────────────────────────

async function main() {
  const cfg = parseArgs()
  if (cfg.waitMode)                         await runWaitMode(cfg)
  else if (cfg.webrtcMode && cfg.targetUid) await runWebrtcChallengeMode(cfg)
  else if (cfg.rankMode)                    await runRankQueueMode(cfg)
  else if (cfg.targetUid)                   await runChallengeMode(cfg)
  else                                      await runBotVsBotMode(cfg)
}

main().catch((e) => { console.error('\n\x1b[31mError:\x1b[0m', e); process.exit(1) })
